apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "nuxeo.fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.nuxeo.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.nuxeo.replicaCount }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.nuxeo.draft }}
        app: {{ template "nuxeo.fullname" . }}
{{- if .Values.nuxeo.podAnnotations }}
      annotations:
{{ toYaml .Values.nuxeo.podAnnotations | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.nuxeo.image.repository }}:{{ .Values.nuxeo.image.tag }}"
        imagePullPolicy: {{ .Values.nuxeo.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nuxeo.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.nuxeo.probePath }}
            port: {{ .Values.nuxeo.service.internalPort }}
          initialDelaySeconds: {{ .Values.nuxeo.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.nuxeo.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.nuxeo.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.nuxeo.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.nuxeo.probePath }}
            port: {{ .Values.nuxeo.service.internalPort }}
          periodSeconds: {{ .Values.nuxeo.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.nuxeo.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.nuxeo.readinessProbe.timeoutSeconds }}
        env:
        - name: NUXEO_PACKAGES
          value: {{ .Values.nuxeo.packages }}
        - name: NUXEO_CLID  
          value: {{ .Values.nuxeo.clid | quote }}  
        volumeMounts:
          - name: nuxeoconf
            mountPath: /docker-entrypoint-initnuxeo.d/
          - name: connect-secret
            mountPath: /opt/nuxeo/connect/ 
          - name: log
            mountPath: /var/log/nuxeo
          - name: binaries
            mountPath: /binaries
      securityContext:
        fsGroup: 1000
      volumes:
      - name: nuxeoconf
        configMap:
          name: {{ template "nuxeo.fullname" . }}-conf 
      - name: connect-secret
        secret:
          secretName: {{ template "nuxeo.fullname" . }}-connect
      - name: binaries
        {{- if .Values.nuxeo.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "nuxeo.fullname" . }}-binaries 
        {{- else }}
        emptyDir: {}
        {{- end }} 
      - name: log
        {{- if .Values.nuxeo.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "nuxeo.fullname" . }}-log 
        {{- else }}
        emptyDir: {}
        {{- end }}  
