apiVersion: v1  
kind: Secret  
metadata:  
  name: {{ template "fullname" . }}-connect
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque  
stringData:
  connect.properties: |-
      {{ if .Values.nuxeo.studio_project  }}
      NUXEO_STUDIO_PROJECT={{ .Values.nuxeo.studio_project | quote }}
      {{ end }}
      {{ if .Values.nuxeo.connect_username  }}
      NUXEO_CONNECT_USERNAME={{ .Values.nuxeo.connect_username | quote }}
      {{ end }}
      {{ if .Values.nuxeo.connect_password  }}
      NUXEO_CONNECT_PASSWORD={{ .Values.nuxeo.connect_password | quote }}
      {{ end }}
