nuxeo:
  webui:
    image:
      repository: jenkins-x-docker-registry:5000/nuxeo/nuxeo-web-ui
      tag: 3.0.0-SNAPSHOT
      pullPolicy: Always
    service:
      type: ClusterIP
      externalPort: 80
      internalPort: 80
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
