nuxeo:
  image:
    repository: nuxeo/nuxeo
    tag: master 
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    externalPort: 80
    internalPort: 8080
    annotations:
      fabric8.io/expose: "true"
      fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
  probePath: /nuxeo/runningstatus
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 10
    timeoutSeconds: 10
  readinessProbe:
    periodSeconds: 10
    initialDelaySeconds: 100
    successThreshold: 1
    timeoutSeconds: 10
    failureThreshold: 3
  terminationGracePeriodSeconds: 10
  mongodb:
    dbname: nuxeo
  postgresql:
    dbname: nuxeo
    username: nuxeo
    password: nuxeo
  elasticsearch:
    clusterName: elasticsearch
    indexName: nuxeo
    deploy: false  
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
  persistence:
    enabled: false
    storageClass: standard
    size:
      binaries: 10Gi
      tmp: 10Gi
    annotations: {}
  custom_params: |-
    ## add any other params that go into nuxeo.conf


## Values from here can be customized https://github.com/helm/charts/blob/master/stable/mongodb/values.yaml
mongodb:
  deploy: false
  usePassword: false

## Override values for postgresql from https://github.com/helm/charts/blob/master/stable/postgresql/values.yaml
postgresql:
  deploy: false
  image:
    tag: 9.6.11
  initdbScripts:
    db-init.sql: |
      CREATE ROLE nuxeo WITH PASSWORD 'nuxeo' LOGIN;
      CREATE DATABASE nuxeo ENCODING 'UTF8' OWNER nuxeo;

## Override values from https://github.com/helm/charts/blob/master/stable/elasticsearch/values.yaml
## these are for a staging cluster only, but it needs 2 masters anyway
elasticsearch:
  deploy: false
  appVersion: "6.2"
  client:
    replicas: 1
  master:
    replicas: 2
  data:
    replicas: 1    

## Override values from https://github.com/helm/charts/blob/master/incubator/kafka/values.yaml
## staging values only, no need for 3 replicas and zoopkeper ( must be 1, 3, kafla needs zookeper)
## see https://github.com/jenkins-x/jx/issues/2504 
kafka:
  deploy: false
  replicas: 1
  zookeeper:
    replicaCount: 1
  prometheus:
    operator:
      enabled: false 

## Override values from https://github.com/helm/charts/blob/master/stable/redis/values.yaml
## staging values only, no need for a cluster
redis:
  deploy: true
  cluster: 
    enabled: false
  usePassword: false
  master:
    persistence:
      enabled: false         

